# Generated by Django 2.2.24 on 2021-11-09 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'тема вопроса',
                'verbose_name_plural': 'темы вопросов',
                'ordering': ('order_key',),
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ваше имя')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='e-mail')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('question', models.CharField(max_length=2000, verbose_name='Вопрос')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 9, 7, 35, 14, 463754), verbose_name='Дата и время')),
                ('answer', tinymce.models.HTMLField(blank=True, max_length=4000, null=True, verbose_name='Ответ')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FaqTheme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('order_key',),
            },
        ),
    ]
