# Generated by Django 2.2.27 on 2022-02-18 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20211111_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FaqTheme', verbose_name='Тема'),
        ),
    ]
