# Generated by Django 2.2.24 on 2021-11-03 05:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_news', '0003_auto_20211102_1308'),
        ('custom_news', '0002_auto_20190830_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNews',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easy_news.News')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('easy_news.news',),
        ),
        migrations.AlterField(
            model_name='newsroot',
            name='bottom_content',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='контент внизу страницы'),
        ),
    ]
