# Generated by Django 2.2.24 on 2021-11-11 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 5, 45, 12, 556069), verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faq.FaqTheme', verbose_name='Тема'),
        ),
    ]
