# Generated by Django 2.2.24 on 2021-11-08 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='E-mail')),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/attachment/source/reviews', verbose_name='Прикрепить Ваше фото')),
                ('date', models.DateField(default=datetime.date(2021, 11, 8), verbose_name='Дата отправки отзыва')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('show', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-date',),
            },
        ),
    ]
