# Generated by Django 2.2.24 on 2022-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0009_auto_20220114_1306_squashed_0020_auto_20220128_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fireproof_types',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Пределы огнестойкости'),
        ),
    ]
