# Generated by Django 2.2.27 on 2022-02-15 12:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0011_auto_20220215_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='fireproof_types',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Пределы огнестойкости'),
        ),
    ]
