# Generated by Django 2.2.28 on 2022-12-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_catalog', '0002_auto_20221206_1014'),
        ('pages', '0010_auto_20211220_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('title', models.TextField(verbose_name='Текст')),
                ('icon', models.FileField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Category', verbose_name='категория')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Блок "каталог"',
                'verbose_name_plural': 'Блок "каталог"',
                'ordering': ['order_key'],
            },
        ),
    ]
