# Generated by Django 2.2.24 on 2022-01-14 13:08

import attachment.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('custom_catalog', '0001_initial'), ('custom_catalog', '0002_auto_20211103_1026'), ('custom_catalog', '0003_auto_20211221_0512'), ('custom_catalog', '0004_auto_20211223_1056'), ('custom_catalog', '0005_remove_section_gallery'), ('custom_catalog', '0006_category_show_on_site'), ('custom_catalog', '0007_auto_20211227_1038'), ('custom_catalog', '0008_auto_20220109_1638')]

    initial = True

    dependencies = [
        ('pages', '0010_auto_20211220_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/doctypes', verbose_name='изображение')),
                ('order_key', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'вид документа',
                'verbose_name_plural': 'виды документов',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='FireResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('image', models.FileField(upload_to='upload/fireresistance', verbose_name='изображение')),
                ('order_key', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'предел огнестойкости',
                'verbose_name_plural': 'пределы огнестойкости',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('width', models.CharField(blank=True, help_text='мм', max_length=255, null=True, verbose_name='ширина')),
                ('height', models.CharField(blank=True, help_text='мм', max_length=255, null=True, verbose_name='высота')),
                ('show_in_filter', models.BooleanField(default=False, verbose_name='Отображать в фильтре')),
                ('fire_resistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.FireResistance', verbose_name='Огнестойкость')),
                ('order_key', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'вид изделия',
                'verbose_name_plural': 'виды изделий',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Facing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'тип отделки',
                'verbose_name_plural': 'типы отделки',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Слаг свойства')),
                ('show_on_filter', models.BooleanField(default=True, verbose_name='Отображать в фильтре')),
                ('show_on_item', models.BooleanField(default=True, verbose_name='отображать на странице товара')),
                ('optional', models.BooleanField(default=False, verbose_name='необязательный')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('cert_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер документа')),
                ('cert_series', models.CharField(blank=True, max_length=255, null=True, verbose_name='серия документа')),
                ('cert_end_date', models.DateField(blank=True, null=True, verbose_name='срок действия документа')),
                ('gost_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГОСТ')),
                ('tu_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='ТУ')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('doc_type', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.DocType', verbose_name='вид документа')),
                ('item_types', models.ManyToManyField(related_name='docs', to='custom_catalog.ItemType', verbose_name='Виды изделий')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('сертификат', 'сертификат'), ('паспорт изделия', 'паспорт изделия'), ('протокол испытаний', 'протокол испытаний'), ('лицензия', 'лицензия'), ('схема конструкции', 'схема конструкции')], max_length=255, null=True, verbose_name='тип документа')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('image', attachment.fields.ImagePreviewField(upload_to='upload/docs', verbose_name='изображение')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_catalog.Doc')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фотографии',
                'ordering': ('order_key',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='название')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена')),
                ('description', tinymce.models.HTMLField(blank=True, default='', verbose_name='описание')),
                ('box_size', models.CharField(default='950 x 2050', max_length=400, verbose_name='размер коробки')),
                ('fireproof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.FireResistance', verbose_name='огнестойкость')),
                ('guarantee', models.IntegerField(default=5, help_text='лет', verbose_name='Гарантия на дверь')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.ItemType', verbose_name='вид изделия')),
                ('production_time', models.IntegerField(default=12, help_text='часов', verbose_name='Срок изготовления')),
                ('square_price', models.CharField(blank=True, default='', max_length=255, verbose_name='цена за квадратный метр')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('bottom_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='контент после списка товаров')),
                ('articles', models.ManyToManyField(blank=True, limit_choices_to={'template': 'pages/article.html'}, related_name='section_articles', to='pages.Page', verbose_name='Статьи')),
                ('delivery_moscow', models.TextField(blank=True, max_length=400, null=True, verbose_name='доставка по Москве и Московской области')),
                ('delivery_russia', models.TextField(blank=True, max_length=400, null=True, verbose_name='Доставка по России')),
                ('guarantee', models.IntegerField(default=5, help_text='лет', verbose_name='Гарантия на дверь')),
                ('installation', models.TextField(blank=True, max_length=400, null=True, verbose_name='установка')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.ItemType', verbose_name='вид изделия')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
                ('product_type', models.CharField(blank=True, choices=[('двери', 'Двери'), ('люки', 'Люки'), ('ворота', 'Ворота'), ('прочие изделия', 'Прочие изделия')], max_length=255, null=True, verbose_name='тип изделия')),
                ('production_time', models.IntegerField(default=12, help_text='часов', verbose_name='Срок изготовления')),
                ('service', models.TextField(blank=True, max_length=400, null=True, verbose_name='гарантийное обслуживание')),
                ('door_samples', models.ForeignKey(blank=True, limit_choices_to={'template': 'pages/gallery.html'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_door_samples', to='pages.Page', verbose_name='примеры дверей')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('default', models.BooleanField(default=False, verbose_name='Использовать по умолчанию')),
                ('name', models.CharField(max_length=400, verbose_name='Введите значение')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_catalog.Property', verbose_name='Параметр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('extra_charge', models.PositiveIntegerField(default=0, verbose_name='наценка')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
                'ordering': ['order_key'],
            },
        ),
        migrations.CreateModel(
            name='FacingPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('image', attachment.fields.ImagePreviewField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='изображение')),
                ('facing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facing_prints', to='custom_catalog.Facing', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'рисунок отделки',
                'verbose_name_plural': 'рисунки отделки',
                'ordering': ('order_key', 'facing'),
            },
        ),
        migrations.CreateModel(
            name='FacingColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('image', attachment.fields.ImagePreviewField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='изображение')),
                ('facing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facing_colors', to='custom_catalog.Facing', verbose_name='Отделка')),
            ],
            options={
                'verbose_name': 'цвет отделки',
                'verbose_name_plural': 'цвета отделки',
                'ordering': ('order_key', 'facing'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='блок контента')),
                ('articles', models.ManyToManyField(blank=True, limit_choices_to={'template': 'pages/article.html'}, related_name='category_articles', to='pages.Page', verbose_name='Статьи')),
                ('products', models.ManyToManyField(blank=True, related_name='category', to='custom_catalog.Product', verbose_name='товары')),
                ('door_samples', models.ForeignKey(blank=True, limit_choices_to={'template': 'pages/gallery.html'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_door_samples', to='pages.Page', verbose_name='примеры дверей')),
                ('show_on_site', models.BooleanField(default=False, verbose_name='отображать на сайте')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('title', models.CharField(max_length=400, verbose_name='название')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='длинное название')),
                ('top_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='контент в начале страницы')),
                ('bottom_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='контент в конце страницы')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'корневая страница',
                'verbose_name_plural': 'корневая страница',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('facing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_facing_id', to='custom_catalog.Facing', verbose_name='Отделка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attachment_image_id', to='custom_catalog.Product', verbose_name='товар')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_attachment_image_id', to='custom_catalog.Section', verbose_name='раздел')),
                ('image', attachment.fields.ImagePreviewField(null=True, upload_to='upload/attachment/source', verbose_name='Изображение')),
                ('side', models.CharField(choices=[('inside', 'Внутренняя'), ('outside', 'Внешняя')], default='inside', max_length=255, verbose_name='Сторона двери')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color_id', to='custom_catalog.FacingColor', verbose_name='Цвет отделки')),
                ('print', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_print_id', to='custom_catalog.FacingPrint', verbose_name='Рисунок отделки')),
            ],
            options={
                'verbose_name': 'Изображение товара с отделкой',
                'verbose_name_plural': 'Изображения товара с отделкой',
                'ordering': ('order_key', 'facing'),
            },
        ),
        migrations.CreateModel(
            name='ImageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('image', attachment.fields.ImagePreviewField(null=True, upload_to='upload/attachment/source', verbose_name='Изображение')),
                ('side', models.CharField(choices=[('inside', 'Внутренняя'), ('outside', 'Внешняя')], default='inside', max_length=255, verbose_name='Сторона двери')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_manager_color_id', to='custom_catalog.FacingColor', verbose_name='Цвет отделки')),
                ('facing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_manager_facing_id', to='custom_catalog.Facing', verbose_name='Отделка')),
                ('print', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_manager_print_id', to='custom_catalog.FacingPrint', verbose_name='Рисунок отделки')),
            ],
            options={
                'verbose_name': 'Менеджер изображений',
                'ordering': ('order_key', 'facing'),
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_parameters', to='custom_catalog.Category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='custom_catalog.Product')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Property', verbose_name='Параметр')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_parameters', to='custom_catalog.Section')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Value', verbose_name='Значение')),
                ('image_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_manager_parameters', to='custom_catalog.ImageManager')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['order_key'],
            },
        ),
    ]
