# Generated by Django 2.2.24 on 2022-01-28 12:02

import attachment.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('custom_catalog', '0009_auto_20220114_1306'), ('custom_catalog', '0010_remove_addparameter_category'), ('custom_catalog', '0011_auto_20220125_1029'), ('custom_catalog', '0012_category_product_type'), ('custom_catalog', '0013_section_show_in_we_produce'), ('custom_catalog', '0014_section_comment'), ('custom_catalog', '0015_section_show_in_our_technologies'), ('custom_catalog', '0016_category_show_in_our_technologies'), ('custom_catalog', '0017_remove_category_show_on_site'), ('custom_catalog', '0018_category_comment'), ('custom_catalog', '0019_product_popular'), ('custom_catalog', '0020_auto_20220128_0918')]

    dependencies = [
        ('custom_catalog', '0008_auto_20220109_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_add_parameters', to='custom_catalog.Category')),
            ],
            options={
                'verbose_name': 'Доп. Параметр',
                'verbose_name_plural': 'Доп. Параметры',
                'ordering': ['order_key'],
            },
        ),
        migrations.AlterModelOptions(
            name='facingcolor',
            options={'ordering': ('order_key',), 'verbose_name': 'цвет отделки', 'verbose_name_plural': 'цвета отделки'},
        ),
        migrations.AlterModelOptions(
            name='facingprint',
            options={'ordering': ('order_key',), 'verbose_name': 'рисунок отделки', 'verbose_name_plural': 'рисунки отделки'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='image_manager',
        ),
        migrations.RemoveField(
            model_name='property',
            name='show_on_item',
        ),
        migrations.AddField(
            model_name='facingcolor',
            name='color',
            field=models.CharField(blank=True, help_text='Например: #fff', max_length=255, null=True, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='bottom_content',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='контент внизу страницы'),
        ),
        migrations.AddField(
            model_name='product',
            name='facing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Facing', verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_on_item_desc',
            field=models.BooleanField(default=False, verbose_name='отображать в описании товара'),
        ),
        migrations.AddField(
            model_name='value',
            name='option_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название опции'),
        ),
        migrations.RemoveField(
            model_name='facingcolor',
            name='facing',
        ),
        migrations.AddField(
            model_name='facingcolor',
            name='facing',
            field=models.ManyToManyField(blank=True, related_name='facing_colors', to='custom_catalog.Facing', verbose_name='Варианты отделки'),
        ),
        migrations.AlterField(
            model_name='facingcolor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='изображение'),
        ),
        migrations.RemoveField(
            model_name='facingprint',
            name='facing',
        ),
        migrations.AddField(
            model_name='facingprint',
            name='facing',
            field=models.ManyToManyField(blank=True, related_name='facing_prints', to='custom_catalog.Facing', verbose_name='Варианты отделки'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=attachment.fields.ImagePreviewField(blank=True, null=True, upload_to='upload/attachment/source', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attachment_image_id', to='custom_catalog.Product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='section',
            name='delivery_moscow',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='доставка по Москве и Московской области'),
        ),
        migrations.AlterField(
            model_name='section',
            name='delivery_russia',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Доставка по России'),
        ),
        migrations.AlterField(
            model_name='section',
            name='installation',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='установка'),
        ),
        migrations.AlterField(
            model_name='section',
            name='service',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='гарантийное обслуживание'),
        ),
        migrations.DeleteModel(
            name='ImageManager',
        ),
        migrations.AddField(
            model_name='addparameter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_add_parameters', to='custom_catalog.Product'),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.Property', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_add_parameters', to='custom_catalog.Section'),
        ),
        migrations.AddField(
            model_name='addparameter',
            name='values',
            field=models.ManyToManyField(blank=True, to='custom_catalog.Value', verbose_name='Доп. параметры'),
        ),
        migrations.RemoveField(
            model_name='addparameter',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='long_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='fireresistance',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/fireresistance', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=400, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.CharField(blank=True, choices=[('двери', 'Двери'), ('люки', 'Люки'), ('ворота', 'Ворота'), ('прочие изделия', 'Прочие изделия')], max_length=255, null=True, verbose_name='тип изделия'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_in_we_produce',
            field=models.BooleanField(default=False, verbose_name='отображать в "Мы производим"'),
        ),
        migrations.AddField(
            model_name='section',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_in_our_technologies',
            field=models.BooleanField(default=False, verbose_name='отображать в "Наши технологии"'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_our_technologies',
            field=models.BooleanField(default=False, verbose_name='отображать в "Наши технологии"'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_on_site',
        ),
        migrations.AddField(
            model_name='category',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='fireproof',
        ),
        migrations.RemoveField(
            model_name='product',
            name='square_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_square',
            field=models.BooleanField(default=False, verbose_name='цена за квадратный метр'),
        ),
    ]
