# Generated by Django 2.2.27 on 2022-02-15 11:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0010_section_fireproof_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='fire_resistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.FireResistance', verbose_name='Огнестойкость'),
        ),
        migrations.AlterField(
            model_name='section',
            name='delivery_moscow',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='доставка по Москве и Московской области'),
        ),
        migrations.AlterField(
            model_name='section',
            name='delivery_russia',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Доставка по России'),
        ),
        migrations.AlterField(
            model_name='section',
            name='installation',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='установка'),
        ),
        migrations.AlterField(
            model_name='section',
            name='service',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='гарантийное обслуживание'),
        ),
    ]
