# Generated by Django 2.2.15 on 2020-10-16 09:58

from django.db import migrations

def create_settings(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Sites = apps.get_model("sites", "Site")
    SiteSettings = apps.get_model("service", "SiteSettings")
    for site in Sites.objects.all():
        SiteSettings.objects.using(db_alias).update_or_create(site_ptr=site)

def delete_settings(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Sites = apps.get_model("sites", "Site")
    SiteSettings = apps.get_model("service", "SiteSettings")
    for site in Sites.objects.all():
        SiteSettings.objects.using(db_alias).filter(site_ptr=site).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_settings, delete_settings),
    ]
