# Generated by Django 2.2.28 on 2022-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'Двери по назначению'), (2, 'Двери по наружной отделке'), (3, 'Двери по особенностям')], null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='section',
            name='group',
            field=models.IntegerField(blank=True, choices=[(1, 'Двери по назначению'), (2, 'Двери по наружной отделке'), (3, 'Двери по особенностям')], null=True, verbose_name='Группа'),
        ),
    ]
