# Generated by Django 2.2.28 on 2022-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0003_auto_20221220_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclude_direct_yml',
            field=models.BooleanField(default=False, verbose_name='Не выгружать в Yandex Директ'),
        ),
    ]
