# Generated by Django 2.2.28 on 2023-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0004_product_exclude_direct_yml'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.CharField(choices=[('asc', 'Сначала дешевые'), ('desc', 'Сначала дорогие'), ('new', 'Новинки сверху')], default='new', max_length=255, verbose_name='Сортировать товары'),
        ),
        migrations.AddField(
            model_name='root',
            name='sort',
            field=models.CharField(choices=[('asc', 'Сначала дешевые'), ('desc', 'Сначала дорогие'), ('new', 'Новинки сверху')], default='new', max_length=255, verbose_name='Сортировать товары'),
        ),
        migrations.AddField(
            model_name='section',
            name='sort',
            field=models.CharField(choices=[('asc', 'Сначала дешевые'), ('desc', 'Сначала дорогие'), ('new', 'Новинки сверху')], default='new', max_length=255, verbose_name='Сортировать товары'),
        ),
    ]
