# Generated by Django 2.2.27 on 2022-02-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_pages', '0002_auto_20211116_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='иконка')),
                ('text', models.CharField(max_length=255, verbose_name='текст')),
                ('bold_text', models.CharField(max_length=255, verbose_name='жирный текст')),
                ('order_key', models.PositiveIntegerField(default=0, verbose_name='')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипы',
                'ordering': ['order_key'],
            },
        ),
    ]
