# Generated by Django 2.2.27 on 2022-04-01 09:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order_key'], 'verbose_name': 'Значение параметра', 'verbose_name_plural': 'Значения параметров'},
        ),
        migrations.AddField(
            model_name='category',
            name='products_by_parameters',
            field=models.ManyToManyField(blank=True, related_name='categories_by_parameters', to='custom_catalog.Product', verbose_name='товары по параметрам'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', to='custom_catalog.Product', verbose_name='товары'),
        ),
        migrations.AlterField(
            model_name='facingcolor',
            name='order_key',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Длинное название'),
        ),
        migrations.AlterField(
            model_name='property',
            name='show_on_item_desc',
            field=models.BooleanField(default=False, verbose_name='отображать в списке кратких характеристик'),
        ),
        migrations.AlterField(
            model_name='section',
            name='fireproof_types',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Пределы огнестойкости'),
        ),
    ]
