# Generated by Django 2.2.27 on 2022-04-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0002_auto_20220401_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_one_side',
            field=models.CharField(blank=True, choices=[('inside', 'Внутренняя'), ('outside', 'Внешняя')], max_length=255, null=True, verbose_name='показывать только одну сторону'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_one_side',
            field=models.CharField(blank=True, choices=[('inside', 'Внутренняя'), ('outside', 'Внешняя')], max_length=255, null=True, verbose_name='показывать только одну сторону'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products_by_parameters',
            field=models.ManyToManyField(blank=True, help_text='Скрытый список', related_name='categories_by_parameters', to='custom_catalog.Product', verbose_name='товары по параметрам'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='fire_resistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_catalog.FireResistance', verbose_name='Огнестойкость'),
        ),
    ]
