# Generated by Django 2.2.27 on 2022-04-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0003_auto_20220408_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc_type',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_catalog.DocType', verbose_name='вид документа'),
        ),
    ]
