# Generated by Django 2.2.27 on 2022-04-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0005_auto_20220421_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_interior_sample',
        ),
        migrations.RemoveField(
            model_name='section',
            name='show_interior_sample',
        ),
        migrations.AlterField(
            model_name='category',
            name='door_samples',
            field=models.ForeignKey(blank=True, limit_choices_to={'template': 'pages/gallery.html'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_door_samples', to='pages.Page', verbose_name='примеры изделий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_samples',
            field=models.ForeignKey(blank=True, limit_choices_to={'template': 'pages/gallery.html'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page', verbose_name='примеры изделий'),
        ),
        migrations.AlterField(
            model_name='section',
            name='door_samples',
            field=models.ForeignKey(blank=True, limit_choices_to={'template': 'pages/gallery.html'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_door_samples', to='pages.Page', verbose_name='примеры изделий'),
        ),
    ]
