# Generated by Django 2.2.27 on 2022-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0006_auto_20220421_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_block_door_samples',
            field=models.BooleanField(default=True, verbose_name='отображать блок "Примеры изделий"'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_interior_sample',
            field=models.CharField(choices=[('show', 'Отображать'), ('hide', 'Скрыть'), ('inherit', 'Наследовать')], default='inherit', max_length=255, verbose_name='блок "пример в интерьере"'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_interior_sample',
            field=models.CharField(choices=[('show', 'Отображать'), ('hide', 'Скрыть'), ('inherit', 'Наследовать')], default='show', max_length=255, verbose_name='блок "пример в интерьере"'),
        ),
    ]
