# Generated by Django 2.2.27 on 2022-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0007_auto_20220421_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_on_yml',
            field=models.BooleanField(default=False, verbose_name='отображать яндекс турбо страницах'),
        ),
    ]
