# Generated by Django 2.2.27 on 2022-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0008_property_show_on_yml'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_side',
            field=models.CharField(choices=[('inside', 'Внутренняя'), ('outside', 'Внешняя')], default='outside', max_length=255, verbose_name='Обложка товара, сторона'),
        ),
        migrations.AlterField(
            model_name='property',
            name='show_on_yml',
            field=models.BooleanField(default=False, verbose_name='отображать в яндекс турбо страницах'),
        ),
    ]
