# Generated by Django 2.2.27 on 2022-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0009_auto_20220517_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='box_size',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='размер коробки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_size',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='размер коробки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='section',
            name='production_time',
            field=models.IntegerField(default=12, help_text='часов', verbose_name='Изготовление'),
        ),
    ]
