# Generated by Django 2.2.27 on 2022-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0010_auto_20220526_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='custom_catalog.Value', verbose_name='список values'),
        ),
    ]
