# Generated by Django 2.2.27 on 2022-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_catalog', '0011_product_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='long_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Длинное название'),
        ),
        migrations.AlterField(
            model_name='section',
            name='long_title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Длинное название'),
        ),
    ]
